### PR TITLE
My contribution

### PR DESCRIPTION
**Pull request by prerak23**
Here i created this branch , there was this folder named cythonized which i did'nt added.
The code that i wrote can be found in the code file -> pysofamyroom/pysofamyroom.pyx
File test_axis_2.py is also one of the file that i created , it is just a copy of test.py with few lines here and there

### CODE REVIEW

**Comment by mpariente** [comment]
This PR should probably be against the main branch in pysofamyroom rather than here, right?

**Comment by robaru** [comment]
Yes, we decided to have sofamyroom and pysofamyroom as distinct repositories.

**Comment by mpariente** [comment]
By default, the PR opens on this repo (which is the usual way contributions are brought back to upstream repos), hence the PR opened here, but that's just an oversight.

**Comment by robaru** [comment]
Thanks for the clarification! :) 
Is there any action that as owner of the repo I am required to do?

**Comment by robaru** [comment]
I have merged the pull-request into the new branch called pysofamyroom.

**Pull request closed without merging**
